erDiagram

users {
	integer id PK
  string name
  string email
	string crypted_password
	string salt
	integer role
}

authentications {
	integer id PK
  integer user_id FK
  string provider
}

smaile_prices {
	integer id PK
	integer user_id FK
	integer price
}

macd_menus {
	integer id PK
	string name
	integer price
}

smaile_prices_macd_menus {
	integer id PK
	integer smaile_price_id FK
	integer  macd_menu_id FK
}

posts {
	integer id PK
	integer user_id FK
	integer smaile_price_id FK
	string body
}

favorites {
	integer id PK
	integer user_id FK
	integer post_id FK
}

users ||--|| authentications: ""
users ||--o{ smaile_prices: ""
smaile_prices ||--o{ smaile_prices_macd_menus: ""
macd_menus ||--o{ smaile_prices_macd_menus: ""
users ||--o{ posts: ""
posts ||--|| smaile_prices:""
users ||--o{ favorites: ""
posts ||--o{ favorites: ""